Repository reactphp/event-loop, pull requests merged in 2018-03, with the labels that each got.

#156 ExtEventLoop: Remove optional EventBaseConfig and make FEATURE_FDS enabled by default
  src/ExtEventLoop.php
  tests/ExtEventLoopTest.php
Labels: BC break, easy pick, maintenance, new feature

#153 Throw BadMethodCallException on manual loop creating when required extension isn't installed
  README.md
  src/ExtEventLoop.php
  src/ExtLibevLoop.php
  src/ExtLibeventLoop.php
Labels: easy pick, help wanted, maintenance

#157 Documentation for high precision timers with millisecond accuracy or below
  README.md
  src/LoopInterface.php
Labels: maintenance

#159 Do not suggest installing outdated event loop extensions
  composer.json
Labels: easy pick, maintenance

#158 Allow throwing Exception if stream resource is not supported
  README.md
  src/LoopInterface.php
Labels: easy pick, maintenance
