Repository reactphp/event-loop, pull requests merged in 2018-04, with the labels that each got.

#147 Reduces fwrite() call length to one chunk
  tests/AbstractLoopTest.php
Labels: easy pick, maintenance

#160 Documentation for run() and stop()
  README.md
  src/LoopInterface.php
Labels: maintenance

#148 Implement ExtEvLoop (PECL ext-ev)
  README.md
  src/ExtEvLoop.php
  src/Factory.php
  tests/ExtEvLoopTest.php
  tests/Timer/AbstractTimerTest.php
  tests/Timer/ExtEvTimerTest.php
  travis-init.sh
Labels: help wanted, new feature

#164 StreamSelectLoop: Improve memory consumption and runtime performance for timers
  src/Timer/Timers.php
Labels: maintenance, new feature

#161 Removes I/O dependency at StreamSelectLoopTest to fix Mac OS X tests
  tests/AbstractLoopTest.php
Labels: bug, easy pick, maintenance
