Repository reactphp/event-loop, pull requests merged in 2019-12, with the labels that each got.

#202 Fix Travis CI builds, do not install libuv on legacy PHP setups
  .travis.yml
Labels: easy pick, maintenance

#201 Add .gitattributes to exclude dev files from exports
  .gitattributes
Labels: maintenance

#203 Fix failing test cases due to inaccurate timers
  tests/Timer/AbstractTimerTest.php
Labels: maintenance

#205 Fix unsupported EventConfig and SEGFAULTs on shutdown for ext-event on Windows
  .travis.yml
  src/ExtEventLoop.php
Labels: bug

#207 ExtUvLoop: Fix reporting connection refused errors
  .travis.yml
  src/ExtUvLoop.php
  tests/AbstractLoopTest.php
Labels: bug, help wanted
