Repository reactphp/event-loop, pull requests merged in 2022-02, with the labels that each got.

#242 Improve test suite to declare and validate helper variables and support running from meta repository (PHP 8.1)
  phpunit.xml.dist
  tests/AbstractLoopTest.php
  tests/ExtEventLoopTest.php
  tests/ExtLibeventLoopTest.php
  tests/bin/01-ticks-loop-class.php
  tests/bin/02-ticks-loop-instance.php
  tests/bin/03-ticks-loop-stop.php
  tests/bin/11-uncaught.php
  tests/bin/12-undefined.php
  tests/bin/21-stop.php
  tests/bin/22-stop-uncaught.php
Labels: maintenance

#243 Fix periodic timer with zero interval for `ExtEvLoop` and legacy `ExtLibevLoop`
  src/ExtEvLoop.php
  src/ExtLibevLoop.php
  tests/Timer/AbstractTimerTest.php
Labels: bug

#245 Improve default `StreamSelectLoop` to report any warnings for invalid streams passed to `stream_select()`
  src/StreamSelectLoop.php
  tests/StreamSelectLoopTest.php
Labels: new feature

#246 Improve performance of `StreamSelectLoop` when no timers are scheduled
  src/Timer/Timers.php
Labels: new feature
